/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import java.util.Calendar;
import java.io.BufferedOutputStream;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.util.Collections;

/**
 *
 * @author IDEMNIAS
 */
public class Buscar extends javax.swing.JFrame {
    Calendar c = Calendar.getInstance();
    /**
     * Creates new form Menu
     */
    public Buscar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregarcontacto = new javax.swing.JButton();
        Agregar = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        calendario = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        listarcontactos = new javax.swing.JButton();
        busqueda = new javax.swing.JButton();
        nombre = new javax.swing.JTextField();
        apellido1 = new javax.swing.JTextField();
        apellido2 = new javax.swing.JTextField();
        telefono1 = new javax.swing.JTextField();
        telefono2 = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        dia = new javax.swing.JTextField();
        mes = new javax.swing.JTextField();
        año = new javax.swing.JTextField();
        nombreb = new javax.swing.JTextField();
        años = new javax.swing.JTextField();
        siguientecontacto = new javax.swing.JButton();
        nombrebuscar = new javax.swing.JButton();
        apellido1b = new javax.swing.JTextField();
        Busquedaapellido1 = new javax.swing.JLabel();
        apellido1buscar = new javax.swing.JButton();
        siguiente = new javax.swing.JLabel();
        Busquedanombre = new javax.swing.JLabel();
        busquedadiferente = new javax.swing.JLabel();
        jLabelmenu = new javax.swing.JLabel();
        agregarcontacto1 = new javax.swing.JLabel();
        agregarcontacto2 = new javax.swing.JLabel();
        jLabelnombre = new javax.swing.JLabel();
        jLabelapellido = new javax.swing.JLabel();
        jLabelapellido2 = new javax.swing.JLabel();
        jLabeltelefono1 = new javax.swing.JLabel();
        jLabeltelefono2 = new javax.swing.JLabel();
        jLabelemail = new javax.swing.JLabel();
        jLabelFechanacimiento = new javax.swing.JLabel();
        jLabeldia = new javax.swing.JLabel();
        jLabelmes = new javax.swing.JLabel();
        jLabelaño = new javax.swing.JLabel();
        Cuaderno = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agregarcontacto.setFont(new java.awt.Font("Simpsonfont", 1, 8)); // NOI18N
        agregarcontacto.setText("AGREGAR");
        agregarcontacto.setBorderPainted(false);
        agregarcontacto.setContentAreaFilled(false);
        agregarcontacto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarcontacto.setFocusable(false);
        agregarcontacto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        agregarcontacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarcontactoActionPerformed(evt);
            }
        });
        getContentPane().add(agregarcontacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 100, 20));

        Agregar.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Busqueda2.png"))); // NOI18N
        Agregar.setBorderPainted(false);
        Agregar.setContentAreaFilled(false);
        Agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Agregar.setFocusable(false);
        Agregar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Busqueda3.png"))); // NOI18N
        Agregar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Busqueda1.png"))); // NOI18N
        Agregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        getContentPane().add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 170, 190));

        menu.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu2.png"))); // NOI18N
        menu.setBorderPainted(false);
        menu.setContentAreaFilled(false);
        menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu.setFocusPainted(false);
        menu.setFocusable(false);
        menu.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu3.png"))); // NOI18N
        menu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu1.png"))); // NOI18N
        menu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 170, 180));

        calendario.setFont(new java.awt.Font("Simpsonfont", 1, 9)); // NOI18N
        calendario.setText("CALENDARIO");
        calendario.setBorderPainted(false);
        calendario.setContentAreaFilled(false);
        calendario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calendario.setFocusable(false);
        calendario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        calendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarioActionPerformed(evt);
            }
        });
        getContentPane().add(calendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(985, 89, 100, 30));

        eliminar.setFont(new java.awt.Font("Simpsonfont", 1, 10)); // NOI18N
        eliminar.setText("ELIMINAR");
        eliminar.setBorderPainted(false);
        eliminar.setContentAreaFilled(false);
        eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminar.setFocusable(false);
        eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 95, 110, 20));

        modificar.setFont(new java.awt.Font("Simpsonfont", 1, 10)); // NOI18N
        modificar.setText("MODIFICAR");
        modificar.setBorderPainted(false);
        modificar.setContentAreaFilled(false);
        modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modificar.setFocusPainted(false);
        modificar.setFocusable(false);
        modificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        getContentPane().add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 95, 110, 20));

        listarcontactos.setFont(new java.awt.Font("Simpsonfont", 1, 8)); // NOI18N
        listarcontactos.setText("LISTAR");
        listarcontactos.setBorderPainted(false);
        listarcontactos.setContentAreaFilled(false);
        listarcontactos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listarcontactos.setFocusable(false);
        listarcontactos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        listarcontactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarcontactosActionPerformed(evt);
            }
        });
        getContentPane().add(listarcontactos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 91, 90, 20));

        busqueda.setFont(new java.awt.Font("Simpsonfont", 1, 10)); // NOI18N
        busqueda.setText("BUSQUEDA");
        busqueda.setBorderPainted(false);
        busqueda.setContentAreaFilled(false);
        busqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        busqueda.setFocusable(false);
        busqueda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaActionPerformed(evt);
            }
        });
        getContentPane().add(busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 93, 100, 20));

        nombre.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        nombre.setForeground(new java.awt.Color(51, 51, 255));
        nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombre.setBorder(null);
        nombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nombre.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        nombre.setEnabled(false);
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 160, 330, 40));

        apellido1.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        apellido1.setForeground(new java.awt.Color(51, 51, 255));
        apellido1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        apellido1.setBorder(null);
        apellido1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        apellido1.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        apellido1.setEnabled(false);
        getContentPane().add(apellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 215, 330, 40));

        apellido2.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        apellido2.setForeground(new java.awt.Color(51, 51, 255));
        apellido2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        apellido2.setBorder(null);
        apellido2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        apellido2.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        apellido2.setEnabled(false);
        getContentPane().add(apellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 270, 330, 40));

        telefono1.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        telefono1.setForeground(new java.awt.Color(51, 51, 255));
        telefono1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        telefono1.setBorder(null);
        telefono1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        telefono1.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        telefono1.setEnabled(false);
        getContentPane().add(telefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 325, 330, 40));

        telefono2.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        telefono2.setForeground(new java.awt.Color(51, 51, 255));
        telefono2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        telefono2.setBorder(null);
        telefono2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        telefono2.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        telefono2.setEnabled(false);
        getContentPane().add(telefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 380, 330, 40));

        email.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        email.setForeground(new java.awt.Color(51, 51, 255));
        email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email.setBorder(null);
        email.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        email.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        email.setEnabled(false);
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 435, 330, 40));

        dia.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        dia.setForeground(new java.awt.Color(51, 51, 255));
        dia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dia.setBorder(null);
        dia.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        dia.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        dia.setEnabled(false);
        dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaActionPerformed(evt);
            }
        });
        getContentPane().add(dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 545, 70, 40));

        mes.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        mes.setForeground(new java.awt.Color(51, 51, 255));
        mes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mes.setBorder(null);
        mes.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        mes.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        mes.setEnabled(false);
        getContentPane().add(mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 545, 70, 40));

        año.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        año.setForeground(new java.awt.Color(51, 51, 255));
        año.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        año.setBorder(null);
        año.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        año.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        año.setEnabled(false);
        getContentPane().add(año, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 545, 160, 40));

        nombreb.setForeground(new java.awt.Color(51, 51, 255));
        nombreb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombreb.setBorder(null);
        getContentPane().add(nombreb, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 330, 40));

        años.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        años.setForeground(new java.awt.Color(51, 51, 255));
        años.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        años.setBorder(null);
        años.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        años.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        años.setEnabled(false);
        años.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añosActionPerformed(evt);
            }
        });
        getContentPane().add(años, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 600, 450, 40));

        siguientecontacto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/siguiente2.png"))); // NOI18N
        siguientecontacto.setBorderPainted(false);
        siguientecontacto.setContentAreaFilled(false);
        siguientecontacto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        siguientecontacto.setEnabled(false);
        siguientecontacto.setFocusPainted(false);
        siguientecontacto.setFocusable(false);
        siguientecontacto.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        siguientecontacto.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/siguiente3.png"))); // NOI18N
        siguientecontacto.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/siguiente1.png"))); // NOI18N
        siguientecontacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguientecontactoActionPerformed(evt);
            }
        });
        getContentPane().add(siguientecontacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 640, 140, 210));

        nombrebuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscarpor2.png"))); // NOI18N
        nombrebuscar.setBorderPainted(false);
        nombrebuscar.setContentAreaFilled(false);
        nombrebuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nombrebuscar.setFocusPainted(false);
        nombrebuscar.setFocusable(false);
        nombrebuscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscarpor3.png"))); // NOI18N
        nombrebuscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscarpor1.png"))); // NOI18N
        nombrebuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrebuscarActionPerformed(evt);
            }
        });
        getContentPane().add(nombrebuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 460, 60));

        apellido1b.setForeground(new java.awt.Color(51, 51, 255));
        apellido1b.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        apellido1b.setBorder(null);
        getContentPane().add(apellido1b, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, 320, 40));

        Busquedaapellido1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Busquedaapellido1.setText("APELLIDO1 : ");
        getContentPane().add(Busquedaapellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 500, 130, -1));

        apellido1buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscarpor2.png"))); // NOI18N
        apellido1buscar.setBorderPainted(false);
        apellido1buscar.setContentAreaFilled(false);
        apellido1buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        apellido1buscar.setFocusPainted(false);
        apellido1buscar.setFocusable(false);
        apellido1buscar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscarpor3.png"))); // NOI18N
        apellido1buscar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscarpor1.png"))); // NOI18N
        apellido1buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellido1buscarActionPerformed(evt);
            }
        });
        getContentPane().add(apellido1buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, 460, 60));

        siguiente.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        siguiente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        siguiente.setText("SIGUIENTE");
        siguiente.setFocusable(false);
        getContentPane().add(siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 705, 150, 50));

        Busquedanombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Busquedanombre.setText("NOMBRE : ");
        getContentPane().add(Busquedanombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 100, -1));

        busquedadiferente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        busquedadiferente.setForeground(new java.awt.Color(255, 51, 51));
        busquedadiferente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        busquedadiferente.setText("BUSQUEDA POR DIFERENTES CAMPOS");
        getContentPane().add(busquedadiferente, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 162, 440, 40));

        jLabelmenu.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabelmenu.setForeground(new java.awt.Color(255, 0, 0));
        jLabelmenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelmenu.setText("MENU");
        jLabelmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelmenu.setFocusable(false);
        getContentPane().add(jLabelmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 80, 20));

        agregarcontacto1.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        agregarcontacto1.setForeground(new java.awt.Color(255, 0, 0));
        agregarcontacto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agregarcontacto1.setText("BUSQUEDA");
        agregarcontacto1.setFocusable(false);
        getContentPane().add(agregarcontacto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 140, 50));

        agregarcontacto2.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        agregarcontacto2.setForeground(new java.awt.Color(255, 0, 0));
        agregarcontacto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agregarcontacto2.setText("CONTACTO");
        agregarcontacto2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        agregarcontacto2.setFocusable(false);
        getContentPane().add(agregarcontacto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 140, 50));

        jLabelnombre.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabelnombre.setText("NOMBRE");
        getContentPane().add(jLabelnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 155, 130, 50));

        jLabelapellido.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabelapellido.setText("APELLIDO 1");
        getContentPane().add(jLabelapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 210, 130, 50));

        jLabelapellido2.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabelapellido2.setText("APELLIDO 2");
        getContentPane().add(jLabelapellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 265, 130, 50));

        jLabeltelefono1.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabeltelefono1.setText("TELEFONO 1");
        getContentPane().add(jLabeltelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 320, 130, 50));

        jLabeltelefono2.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabeltelefono2.setText("TELEFONO 2");
        getContentPane().add(jLabeltelefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 375, 130, 50));

        jLabelemail.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabelemail.setText("EMAIL");
        getContentPane().add(jLabelemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 430, 130, 50));

        jLabelFechanacimiento.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabelFechanacimiento.setText("FECHA NACIMIENTO");
        getContentPane().add(jLabelFechanacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 485, 230, 50));

        jLabeldia.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabeldia.setText("DIA");
        getContentPane().add(jLabeldia, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 540, 40, 50));

        jLabelmes.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabelmes.setText("MES");
        getContentPane().add(jLabelmes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 540, 60, 50));

        jLabelaño.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabelaño.setText("ANO");
        getContentPane().add(jLabelaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 540, 60, 50));

        Cuaderno.setFont(new java.awt.Font("Simpsonfont", 1, 10)); // NOI18N
        Cuaderno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuadernoagenda.png"))); // NOI18N
        Cuaderno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(Cuaderno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wallpapers-los-sipmsons-9.jpg"))); // NOI18N
        fondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1000));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaActionPerformed
        
    }//GEN-LAST:event_diaActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        this.setVisible(false);
        Proyecto.Principal.m.setVisible(true);
    }//GEN-LAST:event_menuActionPerformed

    private void calendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarioActionPerformed
        this.setVisible(false);
        Proyecto.Principal.c.setVisible(true);
    }//GEN-LAST:event_calendarioActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        this.setVisible(false);
        Proyecto.Principal.e.setVisible(true);
    }//GEN-LAST:event_eliminarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        this.setVisible(false);
        Proyecto.Principal.md.setVisible(true);
    }//GEN-LAST:event_modificarActionPerformed

    private void agregarcontactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarcontactoActionPerformed
    this.setVisible(false);
    Proyecto.Principal.a.setVisible(true);
    }//GEN-LAST:event_agregarcontactoActionPerformed

    private void listarcontactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarcontactosActionPerformed
        this.setVisible(false);
        Proyecto.Principal.l.setVisible(true);
    }//GEN-LAST:event_listarcontactosActionPerformed

    private void busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaActionPerformed

    }//GEN-LAST:event_busquedaActionPerformed

    private void siguientecontactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguientecontactoActionPerformed
    String encontrar;
        encontrar=nombreb.getText();
        boolean esta=false;
    if(nombreb.getText().equals(nombre.getText())){    
        for(int i=Proyecto.Principal.posicion+1;i<Proyecto.Principal.Contactos.size();i++){
            if(Proyecto.Principal.Contactos.get(i).getNombre().equals(encontrar)){
                Proyecto.Principal.posicion=i;
                esta=true;
                nombre.setText(Proyecto.Principal.Contactos.get(i).getNombre());
                apellido1.setText(Proyecto.Principal.Contactos.get(i).getApellido1());
                apellido2.setText(Proyecto.Principal.Contactos.get(i).getApellido2());
                telefono1.setText(Proyecto.Principal.Contactos.get(i).getTelefono1());
                telefono2.setText(Proyecto.Principal.Contactos.get(i).getTelefono2());
                email.setText(Proyecto.Principal.Contactos.get(i).getEmail());
                dia.setText(Integer.toString(Proyecto.Principal.Contactos.get(i).getDia()));
                mes.setText(Integer.toString(Proyecto.Principal.Contactos.get(i).getMes()));
                año.setText(Integer.toString(Proyecto.Principal.Contactos.get(i).getAño()));
                años.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.posicion).cumpleaños());
                if(dia.getText().equals("0")&&mes.getText().equals("0")&&año.getText().equals("0")){
                    dia.setText("");
                    mes.setText("");
                    año.setText("");
                }
            i=Proyecto.Principal.Contactos.size();
            }
        }
        if(esta==false){Proyecto.Principal.mensaje="NO HAY MAS CONTACTOS CON ESE NOMBRE";
                Proyecto.Principal.v.setVisible(true);
                siguientecontacto.setEnabled(false);
                nombreb.setText("");
                } 
    }
   
    
    if(apellido1b.getText().equals(apellido1.getText())){    
        for(int i=Proyecto.Principal.posicion+1;i<Proyecto.Principal.Contactos.size();i++){
            if(Proyecto.Principal.Contactos.get(i).getApellido1().equals(encontrar)){
                Proyecto.Principal.posicion=i;
                esta=true;
                nombre.setText(Proyecto.Principal.Contactos.get(i).getNombre());
                apellido1.setText(Proyecto.Principal.Contactos.get(i).getApellido1());
                apellido2.setText(Proyecto.Principal.Contactos.get(i).getApellido2());
                telefono1.setText(Proyecto.Principal.Contactos.get(i).getTelefono1());
                telefono2.setText(Proyecto.Principal.Contactos.get(i).getTelefono2());
                email.setText(Proyecto.Principal.Contactos.get(i).getEmail());
                dia.setText(Integer.toString(Proyecto.Principal.Contactos.get(i).getDia()));
                mes.setText(Integer.toString(Proyecto.Principal.Contactos.get(i).getMes()));
                año.setText(Integer.toString(Proyecto.Principal.Contactos.get(i).getAño()));
                años.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.posicion).cumpleaños());
                if(dia.getText().equals("0")&&mes.getText().equals("0")&&año.getText().equals("0")){
                    dia.setText("");
                    mes.setText("");
                    año.setText("");
                }
            i=Proyecto.Principal.Contactos.size();
            }
        }
        if(esta==false){Proyecto.Principal.mensaje="NO HAY MAS CONTACTOS CON ESE APELLIDO";
                Proyecto.Principal.v.setVisible(true);
                siguientecontacto.setEnabled(false);
                apellido1.setText("");
                } 
    }
    
    }//GEN-LAST:event_siguientecontactoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.nombre.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.apellido1.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.apellido2.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.telefono1.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.telefono2.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.email.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabelFechanacimiento.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.dia.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.mes.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.año.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.años.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabelmenu.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.agregarcontacto1.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.agregarcontacto2.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabelnombre.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabelapellido.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabelapellido2.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabeltelefono1.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabeltelefono2.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabelemail.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabeldia.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabelmes.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabelaño.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.busqueda.setFont(Proyecto.Principal.f.MyFont(1, 10f));
        this.modificar.setFont(Proyecto.Principal.f.MyFont(1, 10f));
        this.eliminar.setFont(Proyecto.Principal.f.MyFont(1, 10f));
        this.calendario.setFont(Proyecto.Principal.f.MyFont(1, 9f));
        this.agregarcontacto.setFont(Proyecto.Principal.f.MyFont(1, 10f));
        this.listarcontactos.setFont(Proyecto.Principal.f.MyFont(1, 10f));
        this.Busquedanombre.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.busquedadiferente.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.nombreb.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.Busquedaapellido1.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.apellido1b.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.siguiente.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        
        
    }//GEN-LAST:event_formWindowActivated

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        
    }//GEN-LAST:event_nombreActionPerformed

    private void nombrebuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrebuscarActionPerformed
     String encontrar;
        encontrar=nombreb.getText();
        Proyecto.Principal.posicion=0;
        boolean esta=false;
        apellido1b.setText("");
        for(int i=0;i<Proyecto.Principal.Contactos.size();i++){
            if(Proyecto.Principal.Contactos.get(i).getNombre().equals(encontrar)){
                Proyecto.Principal.posicion=i;
                siguientecontacto.setEnabled(true);
                esta=true;
                nombre.setText(Proyecto.Principal.Contactos.get(i).getNombre());
                apellido1.setText(Proyecto.Principal.Contactos.get(i).getApellido1());
                apellido2.setText(Proyecto.Principal.Contactos.get(i).getApellido2());
                telefono1.setText(Proyecto.Principal.Contactos.get(i).getTelefono1());
                telefono2.setText(Proyecto.Principal.Contactos.get(i).getTelefono2());
                email.setText(Proyecto.Principal.Contactos.get(i).getEmail());
                dia.setText(Integer.toString(Proyecto.Principal.Contactos.get(i).getDia()));
                mes.setText(Integer.toString(Proyecto.Principal.Contactos.get(i).getMes()));
                año.setText(Integer.toString(Proyecto.Principal.Contactos.get(i).getAño()));
                años.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.posicion).cumpleaños());
                if(dia.getText().equals("0")&&mes.getText().equals("0")&&año.getText().equals("0")){
                    dia.setText("");
                    mes.setText("");
                    año.setText("");
                }
            i=Proyecto.Principal.Contactos.size();
            }
        }
        if(esta==false){Proyecto.Principal.mensaje="CONTACTO NO ENCONTRADO";
                Proyecto.Principal.v.setVisible(true);
                nombre.setText("");
                apellido1.setText("");
                apellido2.setText("");
                telefono1.setText("");
                telefono2.setText("");
                email.setText("");
                dia.setText("");
                mes.setText("");
                año.setText("");
                años.setText("");
                nombreb.setText("");
                }  // TODO add your handling code here:
    }//GEN-LAST:event_nombrebuscarActionPerformed

    private void apellido1buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellido1buscarActionPerformed
    String encontrar;
        encontrar=apellido1b.getText();
        Proyecto.Principal.posicion=0;
        boolean esta=false;
        nombreb.setText("");
        for(int i=0;i<Proyecto.Principal.Contactos.size();i++){
            if(Proyecto.Principal.Contactos.get(i).getApellido1().equals(encontrar)){
                Proyecto.Principal.posicion=i;
                siguientecontacto.setEnabled(true);
                esta=true;
                nombre.setText(Proyecto.Principal.Contactos.get(i).getNombre());
                apellido1.setText(Proyecto.Principal.Contactos.get(i).getApellido1());
                apellido2.setText(Proyecto.Principal.Contactos.get(i).getApellido2());
                telefono1.setText(Proyecto.Principal.Contactos.get(i).getTelefono1());
                telefono2.setText(Proyecto.Principal.Contactos.get(i).getTelefono2());
                email.setText(Proyecto.Principal.Contactos.get(i).getEmail());
                dia.setText(Integer.toString(Proyecto.Principal.Contactos.get(i).getDia()));
                mes.setText(Integer.toString(Proyecto.Principal.Contactos.get(i).getMes()));
                año.setText(Integer.toString(Proyecto.Principal.Contactos.get(i).getAño()));
                años.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.posicion).cumpleaños());
                if(dia.getText().equals("0")&&mes.getText().equals("0")&&año.getText().equals("0")){
                    dia.setText("");
                    mes.setText("");
                    año.setText("");
                }
            i=Proyecto.Principal.Contactos.size();
            }
        }
        if(esta==false){Proyecto.Principal.mensaje="CONTACTO NO ENCONTRADO";
                Proyecto.Principal.v.setVisible(true);
                nombre.setText("");
                apellido1.setText("");
                apellido2.setText("");
                telefono1.setText("");
                telefono2.setText("");
                email.setText("");
                dia.setText("");
                mes.setText("");
                año.setText("");
                años.setText("");
                nombreb.setText("");; }
    }//GEN-LAST:event_apellido1buscarActionPerformed

    private void añosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_añosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buscar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JLabel Busquedaapellido1;
    private javax.swing.JLabel Busquedanombre;
    private javax.swing.JLabel Cuaderno;
    private javax.swing.JButton agregarcontacto;
    private javax.swing.JLabel agregarcontacto1;
    private javax.swing.JLabel agregarcontacto2;
    private javax.swing.JTextField apellido1;
    private javax.swing.JTextField apellido1b;
    private javax.swing.JButton apellido1buscar;
    private javax.swing.JTextField apellido2;
    private javax.swing.JTextField año;
    private javax.swing.JTextField años;
    private javax.swing.JButton busqueda;
    private javax.swing.JLabel busquedadiferente;
    private javax.swing.JButton calendario;
    private javax.swing.JTextField dia;
    private javax.swing.JButton eliminar;
    private javax.swing.JTextField email;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabelFechanacimiento;
    private javax.swing.JLabel jLabelapellido;
    private javax.swing.JLabel jLabelapellido2;
    private javax.swing.JLabel jLabelaño;
    private javax.swing.JLabel jLabeldia;
    private javax.swing.JLabel jLabelemail;
    private javax.swing.JLabel jLabelmenu;
    private javax.swing.JLabel jLabelmes;
    private javax.swing.JLabel jLabelnombre;
    private javax.swing.JLabel jLabeltelefono1;
    private javax.swing.JLabel jLabeltelefono2;
    private javax.swing.JButton listarcontactos;
    private javax.swing.JButton menu;
    private javax.swing.JTextField mes;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField nombreb;
    private javax.swing.JButton nombrebuscar;
    private javax.swing.JLabel siguiente;
    private javax.swing.JButton siguientecontacto;
    private javax.swing.JTextField telefono1;
    private javax.swing.JTextField telefono2;
    // End of variables declaration//GEN-END:variables
}
