/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import java.util.Calendar;
import java.io.BufferedOutputStream;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Calendar;

/**
 *
 * @author IDEMNIAS
 */
public class Calendario extends javax.swing.JFrame {
    Calendar c = Calendar.getInstance();
    /**
     * Creates new form Menu
     */
    public Calendario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregarcontacto = new javax.swing.JButton();
        Agregar = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        calendario = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        listarcontactos = new javax.swing.JButton();
        busqueda = new javax.swing.JButton();
        fecha10 = new javax.swing.JTextField();
        fecha9 = new javax.swing.JTextField();
        fecha8 = new javax.swing.JTextField();
        fecha7 = new javax.swing.JTextField();
        fecha6 = new javax.swing.JTextField();
        fecha1 = new javax.swing.JTextField();
        fecha2 = new javax.swing.JTextField();
        fecha3 = new javax.swing.JTextField();
        fecha4 = new javax.swing.JTextField();
        fecha5 = new javax.swing.JTextField();
        agregarcontact = new javax.swing.JLabel();
        jLabelmenu = new javax.swing.JLabel();
        agregarcontacto1 = new javax.swing.JLabel();
        Cuaderno = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agregarcontacto.setFont(new java.awt.Font("Simpsonfont", 1, 8)); // NOI18N
        agregarcontacto.setText("AGREGAR");
        agregarcontacto.setBorderPainted(false);
        agregarcontacto.setContentAreaFilled(false);
        agregarcontacto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarcontacto.setFocusable(false);
        agregarcontacto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        agregarcontacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarcontactoActionPerformed(evt);
            }
        });
        getContentPane().add(agregarcontacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 100, 20));

        Agregar.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendario2.png"))); // NOI18N
        Agregar.setBorderPainted(false);
        Agregar.setContentAreaFilled(false);
        Agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Agregar.setFocusable(false);
        Agregar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendario3.png"))); // NOI18N
        Agregar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendario1.png"))); // NOI18N
        Agregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        getContentPane().add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 170, 170));

        menu.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu2.png"))); // NOI18N
        menu.setBorderPainted(false);
        menu.setContentAreaFilled(false);
        menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu.setFocusPainted(false);
        menu.setFocusable(false);
        menu.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu3.png"))); // NOI18N
        menu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu1.png"))); // NOI18N
        menu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 170, 180));

        calendario.setFont(new java.awt.Font("Simpsonfont", 1, 9)); // NOI18N
        calendario.setText("CALENDARIO");
        calendario.setBorderPainted(false);
        calendario.setContentAreaFilled(false);
        calendario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calendario.setFocusable(false);
        calendario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        calendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarioActionPerformed(evt);
            }
        });
        getContentPane().add(calendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(985, 89, 100, 30));

        eliminar.setFont(new java.awt.Font("Simpsonfont", 1, 10)); // NOI18N
        eliminar.setText("ELIMINAR");
        eliminar.setBorderPainted(false);
        eliminar.setContentAreaFilled(false);
        eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminar.setFocusable(false);
        eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 95, 110, 20));

        modificar.setFont(new java.awt.Font("Simpsonfont", 1, 10)); // NOI18N
        modificar.setText("MODIFICAR");
        modificar.setBorderPainted(false);
        modificar.setContentAreaFilled(false);
        modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modificar.setFocusable(false);
        modificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        getContentPane().add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 95, 110, 20));

        listarcontactos.setFont(new java.awt.Font("Simpsonfont", 1, 8)); // NOI18N
        listarcontactos.setText("LISTAR");
        listarcontactos.setBorderPainted(false);
        listarcontactos.setContentAreaFilled(false);
        listarcontactos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listarcontactos.setFocusable(false);
        listarcontactos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        listarcontactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarcontactosActionPerformed(evt);
            }
        });
        getContentPane().add(listarcontactos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 91, 90, 20));

        busqueda.setFont(new java.awt.Font("Simpsonfont", 1, 10)); // NOI18N
        busqueda.setText("BUSQUEDA");
        busqueda.setBorderPainted(false);
        busqueda.setContentAreaFilled(false);
        busqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        busqueda.setFocusPainted(false);
        busqueda.setFocusable(false);
        busqueda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaActionPerformed(evt);
            }
        });
        getContentPane().add(busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 93, 100, 20));

        fecha10.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        fecha10.setForeground(new java.awt.Color(51, 51, 255));
        fecha10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fecha10.setBorder(null);
        fecha10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fecha10.setFocusable(false);
        getContentPane().add(fecha10, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 815, 490, 50));

        fecha9.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        fecha9.setForeground(new java.awt.Color(51, 51, 255));
        fecha9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fecha9.setBorder(null);
        fecha9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fecha9.setFocusable(false);
        getContentPane().add(fecha9, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 760, 490, 50));

        fecha8.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        fecha8.setForeground(new java.awt.Color(51, 51, 255));
        fecha8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fecha8.setBorder(null);
        fecha8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fecha8.setFocusable(false);
        getContentPane().add(fecha8, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 705, 490, 50));

        fecha7.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        fecha7.setForeground(new java.awt.Color(51, 51, 255));
        fecha7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fecha7.setBorder(null);
        fecha7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fecha7.setFocusable(false);
        getContentPane().add(fecha7, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 650, 490, 50));

        fecha6.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        fecha6.setForeground(new java.awt.Color(51, 51, 255));
        fecha6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fecha6.setBorder(null);
        fecha6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fecha6.setFocusable(false);
        getContentPane().add(fecha6, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 595, 490, 50));

        fecha1.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        fecha1.setForeground(new java.awt.Color(51, 51, 255));
        fecha1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fecha1.setBorder(null);
        fecha1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fecha1.setFocusable(false);
        getContentPane().add(fecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 595, 490, 50));

        fecha2.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        fecha2.setForeground(new java.awt.Color(51, 51, 255));
        fecha2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fecha2.setBorder(null);
        fecha2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fecha2.setFocusable(false);
        getContentPane().add(fecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 650, 490, 50));

        fecha3.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        fecha3.setForeground(new java.awt.Color(51, 51, 255));
        fecha3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fecha3.setBorder(null);
        fecha3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fecha3.setFocusable(false);
        getContentPane().add(fecha3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 705, 490, 50));

        fecha4.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        fecha4.setForeground(new java.awt.Color(51, 51, 255));
        fecha4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fecha4.setBorder(null);
        fecha4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fecha4.setFocusable(false);
        getContentPane().add(fecha4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 760, 490, 50));

        fecha5.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        fecha5.setForeground(new java.awt.Color(51, 51, 255));
        fecha5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fecha5.setBorder(null);
        fecha5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fecha5.setFocusable(false);
        getContentPane().add(fecha5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 815, 490, 50));

        agregarcontact.setBackground(new java.awt.Color(255, 255, 255));
        agregarcontact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agregarcontact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/simpsons_personajes.jpg"))); // NOI18N
        agregarcontact.setToolTipText("");
        agregarcontact.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        agregarcontact.setFocusable(false);
        agregarcontact.setOpaque(true);
        getContentPane().add(agregarcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 115, 1120, 480));

        jLabelmenu.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabelmenu.setForeground(new java.awt.Color(255, 0, 0));
        jLabelmenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelmenu.setText("MENU");
        jLabelmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelmenu.setFocusable(false);
        getContentPane().add(jLabelmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 80, 20));

        agregarcontacto1.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        agregarcontacto1.setForeground(new java.awt.Color(255, 0, 0));
        agregarcontacto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agregarcontacto1.setText("CALENDARIO");
        agregarcontacto1.setFocusable(false);
        getContentPane().add(agregarcontacto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 170, 50));

        Cuaderno.setFont(new java.awt.Font("Simpsonfont", 1, 10)); // NOI18N
        Cuaderno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuadernoagenda.png"))); // NOI18N
        Cuaderno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Cuaderno.setFocusable(false);
        getContentPane().add(Cuaderno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wallpapers-los-sipmsons-9.jpg"))); // NOI18N
        fondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1000));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        this.setVisible(false);
        Proyecto.Principal.m.setVisible(true);
    }//GEN-LAST:event_menuActionPerformed

    private void calendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarioActionPerformed

    }//GEN-LAST:event_calendarioActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        this.setVisible(false);
        Proyecto.Principal.e.setVisible(true);
    }//GEN-LAST:event_eliminarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        this.setVisible(false);
        Proyecto.Principal.md.setVisible(true);
    }//GEN-LAST:event_modificarActionPerformed

    private void agregarcontactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarcontactoActionPerformed
        this.setVisible(false);
        Proyecto.Principal.a.setVisible(true);
    }//GEN-LAST:event_agregarcontactoActionPerformed

    private void listarcontactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarcontactosActionPerformed
        this.setVisible(false);
        Proyecto.Principal.l.setVisible(true);
    }//GEN-LAST:event_listarcontactosActionPerformed

    private void busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaActionPerformed
        this.setVisible(false);
        Proyecto.Principal.b.setVisible(true);
    }//GEN-LAST:event_busquedaActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.fecha1.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.fecha2.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.fecha3.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.fecha4.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.fecha5.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.fecha6.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.fecha7.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.fecha8.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.fecha9.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.fecha10.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabelmenu.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.agregarcontacto1.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.busqueda.setFont(Proyecto.Principal.f.MyFont(1, 10f));
        this.modificar.setFont(Proyecto.Principal.f.MyFont(1, 10f));
        this.eliminar.setFont(Proyecto.Principal.f.MyFont(1, 10f));
        this.calendario.setFont(Proyecto.Principal.f.MyFont(1, 9f));
        this.agregarcontacto.setFont(Proyecto.Principal.f.MyFont(1, 10f));
        this.listarcontactos.setFont(Proyecto.Principal.f.MyFont(1, 10f));
        
        /**
         * Poner fechas por dia y mes
         */
        Comparator<Contacto> comparator = new Comparator<Contacto>() {
    public int compare( Contacto a, Contacto b ) {
        int resultado = Integer.compare(a.getMes(),b.getMes()); 
        if ( resultado != 0 ) { return resultado; }
        resultado = Integer.compare(a.getDia(),b.getDia()); 
        if ( resultado != 0 ) { return resultado;} 
        return resultado;
    }
};
Collections.sort(Proyecto.Principal.Contactos, comparator);
ArrayList <Contacto> calendario = new ArrayList <Contacto> () ;
Calendar c = Calendar.getInstance();
    for(int i=0;i<Proyecto.Principal.Contactos.size();i++){
        if(Proyecto.Principal.Contactos.get(i).getMes()==c.get(Calendar.MONTH)&&
           Proyecto.Principal.Contactos.get(i).getDia()>=c.get(Calendar.DATE)){
            Contacto aux = new Contacto (Proyecto.Principal.Contactos.get(i).getNombre(),
                    Proyecto.Principal.Contactos.get(i).getDia(),
                    Proyecto.Principal.Contactos.get(i).getMes(),
                    Proyecto.Principal.Contactos.get(i).getAño());
            calendario.add(aux);
        }
        if(Proyecto.Principal.Contactos.get(i).getMes()>c.get(Calendar.MONTH)){
            Contacto aux = new Contacto (Proyecto.Principal.Contactos.get(i).getNombre(),
                    Proyecto.Principal.Contactos.get(i).getDia(),
                    Proyecto.Principal.Contactos.get(i).getMes(),
                    Proyecto.Principal.Contactos.get(i).getAño());
            calendario.add(aux);
        }
    }
    for(int i=0;i<calendario.size();i++){
        if(i==0){fecha1.setText(calendario.get(i).fechacumpleaños());}
        if(i==1){fecha2.setText(calendario.get(i).fechacumpleaños());}
        if(i==2){fecha3.setText(calendario.get(i).fechacumpleaños());}
        if(i==3){fecha4.setText(calendario.get(i).fechacumpleaños());}
        if(i==4){fecha5.setText(calendario.get(i).fechacumpleaños());}
        if(i==5){fecha6.setText(calendario.get(i).fechacumpleaños());}
        if(i==6){fecha7.setText(calendario.get(i).fechacumpleaños());}
        if(i==7){fecha8.setText(calendario.get(i).fechacumpleaños());}
        if(i==8){fecha9.setText(calendario.get(i).fechacumpleaños());}
        if(i==9){fecha10.setText(calendario.get(i).fechacumpleaños());}
        }
    Collections.sort(Proyecto.Principal.Contactos);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calendario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calendario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JLabel Cuaderno;
    private javax.swing.JLabel agregarcontact;
    private javax.swing.JButton agregarcontacto;
    private javax.swing.JLabel agregarcontacto1;
    private javax.swing.JButton busqueda;
    private javax.swing.JButton calendario;
    private javax.swing.JButton eliminar;
    private javax.swing.JTextField fecha1;
    private javax.swing.JTextField fecha10;
    private javax.swing.JTextField fecha2;
    private javax.swing.JTextField fecha3;
    private javax.swing.JTextField fecha4;
    private javax.swing.JTextField fecha5;
    private javax.swing.JTextField fecha6;
    private javax.swing.JTextField fecha7;
    private javax.swing.JTextField fecha8;
    private javax.swing.JTextField fecha9;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabelmenu;
    private javax.swing.JButton listarcontactos;
    private javax.swing.JButton menu;
    private javax.swing.JButton modificar;
    // End of variables declaration//GEN-END:variables
}
