/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import java.util.Calendar;
import java.io.BufferedOutputStream;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.util.Collections;

/**
 *
 * @author IDEMNIAS
 */
public class Eliminar extends javax.swing.JFrame {
    Calendar c = Calendar.getInstance();
    /**
     * Creates new form Menu
     */
    public Eliminar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregarcontacto = new javax.swing.JButton();
        Agregar = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        calendario = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        listarcontactos = new javax.swing.JButton();
        busqueda = new javax.swing.JButton();
        nombre = new javax.swing.JTextField();
        apellido1 = new javax.swing.JTextField();
        apellido2 = new javax.swing.JTextField();
        telefono1 = new javax.swing.JTextField();
        telefono2 = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        dia = new javax.swing.JTextField();
        mes = new javax.swing.JTextField();
        año = new javax.swing.JTextField();
        telefonoabuscar = new javax.swing.JTextField();
        telefonomodificar = new javax.swing.JButton();
        Enviar = new javax.swing.JButton();
        carteleliminar = new javax.swing.JLabel();
        presionar = new javax.swing.JLabel();
        Telefonoabuscar1 = new javax.swing.JLabel();
        Telefonoabuscar2 = new javax.swing.JLabel();
        jLabelmenu = new javax.swing.JLabel();
        agregarcontacto1 = new javax.swing.JLabel();
        agregarcontacto2 = new javax.swing.JLabel();
        jLabelnombre = new javax.swing.JLabel();
        jLabelapellido = new javax.swing.JLabel();
        jLabelapellido2 = new javax.swing.JLabel();
        jLabeltelefono1 = new javax.swing.JLabel();
        jLabeltelefono2 = new javax.swing.JLabel();
        jLabelemail = new javax.swing.JLabel();
        jLabelFechanacimiento = new javax.swing.JLabel();
        jLabeldia = new javax.swing.JLabel();
        jLabelmes = new javax.swing.JLabel();
        jLabelaño = new javax.swing.JLabel();
        Cuaderno = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agregarcontacto.setFont(new java.awt.Font("Simpsonfont", 1, 8)); // NOI18N
        agregarcontacto.setText("AGREGAR");
        agregarcontacto.setBorderPainted(false);
        agregarcontacto.setContentAreaFilled(false);
        agregarcontacto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarcontacto.setFocusable(false);
        agregarcontacto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        agregarcontacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarcontactoActionPerformed(evt);
            }
        });
        getContentPane().add(agregarcontacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 100, 20));

        Agregar.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar homer2.png"))); // NOI18N
        Agregar.setBorderPainted(false);
        Agregar.setContentAreaFilled(false);
        Agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Agregar.setFocusable(false);
        Agregar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar homer3.png"))); // NOI18N
        Agregar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar homer1.png"))); // NOI18N
        Agregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        getContentPane().add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 170, 170));

        menu.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu2.png"))); // NOI18N
        menu.setBorderPainted(false);
        menu.setContentAreaFilled(false);
        menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu.setFocusPainted(false);
        menu.setFocusable(false);
        menu.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu3.png"))); // NOI18N
        menu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu1.png"))); // NOI18N
        menu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 170, 180));

        calendario.setFont(new java.awt.Font("Simpsonfont", 1, 9)); // NOI18N
        calendario.setText("CALENDARIO");
        calendario.setBorderPainted(false);
        calendario.setContentAreaFilled(false);
        calendario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calendario.setFocusable(false);
        calendario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        calendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarioActionPerformed(evt);
            }
        });
        getContentPane().add(calendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(985, 89, 100, 30));

        eliminar.setFont(new java.awt.Font("Simpsonfont", 1, 10)); // NOI18N
        eliminar.setText("ELIMINAR");
        eliminar.setBorderPainted(false);
        eliminar.setContentAreaFilled(false);
        eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminar.setFocusable(false);
        eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 95, 110, 20));

        modificar.setFont(new java.awt.Font("Simpsonfont", 1, 10)); // NOI18N
        modificar.setText("MODIFICAR");
        modificar.setBorderPainted(false);
        modificar.setContentAreaFilled(false);
        modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modificar.setFocusPainted(false);
        modificar.setFocusable(false);
        modificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        getContentPane().add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(639, 95, 110, 20));

        listarcontactos.setFont(new java.awt.Font("Simpsonfont", 1, 8)); // NOI18N
        listarcontactos.setText("LISTAR");
        listarcontactos.setBorderPainted(false);
        listarcontactos.setContentAreaFilled(false);
        listarcontactos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listarcontactos.setFocusable(false);
        listarcontactos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        listarcontactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarcontactosActionPerformed(evt);
            }
        });
        getContentPane().add(listarcontactos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 91, 90, 20));

        busqueda.setFont(new java.awt.Font("Simpsonfont", 1, 10)); // NOI18N
        busqueda.setText("BUSQUEDA");
        busqueda.setBorderPainted(false);
        busqueda.setContentAreaFilled(false);
        busqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        busqueda.setFocusable(false);
        busqueda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaActionPerformed(evt);
            }
        });
        getContentPane().add(busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 93, 100, 20));

        nombre.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        nombre.setForeground(new java.awt.Color(51, 51, 255));
        nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombre.setBorder(null);
        nombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nombre.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        nombre.setEnabled(false);
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 160, 330, 40));

        apellido1.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        apellido1.setForeground(new java.awt.Color(51, 51, 255));
        apellido1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        apellido1.setBorder(null);
        apellido1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        apellido1.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        apellido1.setEnabled(false);
        getContentPane().add(apellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 215, 330, 40));

        apellido2.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        apellido2.setForeground(new java.awt.Color(51, 51, 255));
        apellido2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        apellido2.setBorder(null);
        apellido2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        apellido2.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        apellido2.setEnabled(false);
        getContentPane().add(apellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 270, 330, 40));

        telefono1.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        telefono1.setForeground(new java.awt.Color(51, 51, 255));
        telefono1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        telefono1.setBorder(null);
        telefono1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        telefono1.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        telefono1.setEnabled(false);
        getContentPane().add(telefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 325, 330, 40));

        telefono2.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        telefono2.setForeground(new java.awt.Color(51, 51, 255));
        telefono2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        telefono2.setBorder(null);
        telefono2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        telefono2.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        telefono2.setEnabled(false);
        getContentPane().add(telefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 380, 330, 40));

        email.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        email.setForeground(new java.awt.Color(51, 51, 255));
        email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email.setBorder(null);
        email.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        email.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        email.setEnabled(false);
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 435, 330, 40));

        dia.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        dia.setForeground(new java.awt.Color(51, 51, 255));
        dia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dia.setBorder(null);
        dia.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        dia.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        dia.setEnabled(false);
        dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaActionPerformed(evt);
            }
        });
        getContentPane().add(dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 545, 70, 40));

        mes.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        mes.setForeground(new java.awt.Color(51, 51, 255));
        mes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mes.setBorder(null);
        mes.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        mes.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        mes.setEnabled(false);
        getContentPane().add(mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 545, 70, 40));

        año.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        año.setForeground(new java.awt.Color(51, 51, 255));
        año.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        año.setBorder(null);
        año.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        año.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        año.setEnabled(false);
        getContentPane().add(año, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 545, 160, 40));

        telefonoabuscar.setForeground(new java.awt.Color(51, 51, 255));
        telefonoabuscar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        telefonoabuscar.setBorder(null);
        getContentPane().add(telefonoabuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 215, 360, 40));

        telefonomodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/telefonomodificar2.png"))); // NOI18N
        telefonomodificar.setBorderPainted(false);
        telefonomodificar.setContentAreaFilled(false);
        telefonomodificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        telefonomodificar.setFocusPainted(false);
        telefonomodificar.setFocusable(false);
        telefonomodificar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/telefonomodificar3.png"))); // NOI18N
        telefonomodificar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/telefonomodificar1.png"))); // NOI18N
        telefonomodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonomodificarActionPerformed(evt);
            }
        });
        getContentPane().add(telefonomodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 503, 460, 340));

        Enviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar2.png"))); // NOI18N
        Enviar.setBorderPainted(false);
        Enviar.setContentAreaFilled(false);
        Enviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Enviar.setFocusPainted(false);
        Enviar.setFocusable(false);
        Enviar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar3.png"))); // NOI18N
        Enviar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar1.png"))); // NOI18N
        Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarActionPerformed(evt);
            }
        });
        getContentPane().add(Enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 590, 260, 250));

        carteleliminar.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        carteleliminar.setForeground(new java.awt.Color(255, 51, 51));
        carteleliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carteleliminar.setText("ELIMINAR");
        getContentPane().add(carteleliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 650, 170, 50));

        presionar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        presionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        presionar.setText("PRESIONAR AQUI ABAJO PARA BUSCAR");
        getContentPane().add(presionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 460, 50));

        Telefonoabuscar1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Telefonoabuscar1.setText("TEL : ");
        getContentPane().add(Telefonoabuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 225, -1, -1));

        Telefonoabuscar2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Telefonoabuscar2.setForeground(new java.awt.Color(255, 51, 51));
        Telefonoabuscar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Telefonoabuscar2.setText("TELEFONO A BUSCAR");
        getContentPane().add(Telefonoabuscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 260, 40));

        jLabelmenu.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabelmenu.setForeground(new java.awt.Color(255, 0, 0));
        jLabelmenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelmenu.setText("MENU");
        jLabelmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelmenu.setFocusable(false);
        getContentPane().add(jLabelmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 80, 20));

        agregarcontacto1.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        agregarcontacto1.setForeground(new java.awt.Color(255, 0, 0));
        agregarcontacto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agregarcontacto1.setText("MODIFICAR");
        agregarcontacto1.setFocusable(false);
        getContentPane().add(agregarcontacto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 140, 50));

        agregarcontacto2.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        agregarcontacto2.setForeground(new java.awt.Color(255, 0, 0));
        agregarcontacto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agregarcontacto2.setText("CONTACTO");
        agregarcontacto2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        agregarcontacto2.setFocusable(false);
        getContentPane().add(agregarcontacto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 140, 50));

        jLabelnombre.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabelnombre.setText("NOMBRE");
        getContentPane().add(jLabelnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 155, 130, 50));

        jLabelapellido.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabelapellido.setText("APELLIDO 1");
        getContentPane().add(jLabelapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 210, 130, 50));

        jLabelapellido2.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabelapellido2.setText("APELLIDO 2");
        getContentPane().add(jLabelapellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 265, 130, 50));

        jLabeltelefono1.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabeltelefono1.setText("TELEFONO 1");
        getContentPane().add(jLabeltelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 320, 130, 50));

        jLabeltelefono2.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabeltelefono2.setText("TELEFONO 2");
        getContentPane().add(jLabeltelefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 375, 130, 50));

        jLabelemail.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabelemail.setText("EMAIL");
        getContentPane().add(jLabelemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 430, 130, 50));

        jLabelFechanacimiento.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabelFechanacimiento.setText("FECHA NACIMIENTO");
        getContentPane().add(jLabelFechanacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 485, 230, 50));

        jLabeldia.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabeldia.setText("DIA");
        getContentPane().add(jLabeldia, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 540, 40, 50));

        jLabelmes.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabelmes.setText("MES");
        getContentPane().add(jLabelmes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 540, 60, 50));

        jLabelaño.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabelaño.setText("ANO");
        getContentPane().add(jLabelaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 540, 60, 50));

        Cuaderno.setFont(new java.awt.Font("Simpsonfont", 1, 10)); // NOI18N
        Cuaderno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuadernoagenda.png"))); // NOI18N
        Cuaderno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(Cuaderno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wallpapers-los-sipmsons-9.jpg"))); // NOI18N
        fondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1000));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaActionPerformed
        
    }//GEN-LAST:event_diaActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        this.setVisible(false);
        Proyecto.Principal.m.setVisible(true);
    }//GEN-LAST:event_menuActionPerformed

    private void calendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarioActionPerformed
        this.setVisible(false);
        Proyecto.Principal.c.setVisible(true);
    }//GEN-LAST:event_calendarioActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed

    }//GEN-LAST:event_eliminarActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        this.setVisible(false);
        Proyecto.Principal.md.setVisible(true);
    }//GEN-LAST:event_modificarActionPerformed

    private void agregarcontactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarcontactoActionPerformed
    this.setVisible(false);
    Proyecto.Principal.a.setVisible(true);
    }//GEN-LAST:event_agregarcontactoActionPerformed

    private void listarcontactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarcontactosActionPerformed
        this.setVisible(false);
        Proyecto.Principal.l.setVisible(true);
    }//GEN-LAST:event_listarcontactosActionPerformed

    private void busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaActionPerformed
        this.setVisible(false);
        Proyecto.Principal.b.setVisible(true);
    }//GEN-LAST:event_busquedaActionPerformed

    private void EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarActionPerformed
    if(nombre.getText().equals("")&&telefono1.getText().equals("")){
        Proyecto.Principal.mensaje="ESPECIFIQUE CONTACTO";
        Proyecto.Principal.v.setVisible(true);
    }
    else{
        Proyecto.Principal.Contactos.remove(Proyecto.Principal.posicion);
        Collections.sort(Proyecto.Principal.Contactos);
        nombre.setText("");
       apellido1.setText("");
       apellido2.setText("");
       telefono1.setText("");
       telefono2.setText("");
       email.setText("");
       dia.setText("");
       mes.setText("");
       año.setText("");            
       telefonoabuscar.setText("");
    }
    }//GEN-LAST:event_EnviarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.nombre.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.apellido1.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.apellido2.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.telefono1.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.telefono2.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.email.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabelFechanacimiento.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.dia.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.mes.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.año.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabelmenu.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.agregarcontacto1.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.agregarcontacto2.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabelnombre.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabelapellido.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabelapellido2.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabeltelefono1.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabeltelefono2.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabelemail.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabeldia.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabelmes.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabelaño.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.busqueda.setFont(Proyecto.Principal.f.MyFont(1, 10f));
        this.modificar.setFont(Proyecto.Principal.f.MyFont(1, 10f));
        this.eliminar.setFont(Proyecto.Principal.f.MyFont(1, 10f));
        this.calendario.setFont(Proyecto.Principal.f.MyFont(1, 9f));
        this.agregarcontacto.setFont(Proyecto.Principal.f.MyFont(1, 10f));
        this.listarcontactos.setFont(Proyecto.Principal.f.MyFont(1, 10f));
        this.Telefonoabuscar1.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.Telefonoabuscar2.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.telefonoabuscar.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.presionar.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.carteleliminar.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        
    }//GEN-LAST:event_formWindowActivated

    private void telefonomodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonomodificarActionPerformed
        String encontrar;
        encontrar=telefonoabuscar.getText();
        boolean esta=false;
        for(int i=0;i<Proyecto.Principal.Contactos.size();i++){
            if(Proyecto.Principal.Contactos.get(i).getTelefono1().equals(encontrar)){
                Proyecto.Principal.posicion=i;
                esta=true;
                nombre.setText(Proyecto.Principal.Contactos.get(i).getNombre());
                apellido1.setText(Proyecto.Principal.Contactos.get(i).getApellido1());
                apellido2.setText(Proyecto.Principal.Contactos.get(i).getApellido2());
                telefono1.setText(Proyecto.Principal.Contactos.get(i).getTelefono1());
                telefono2.setText(Proyecto.Principal.Contactos.get(i).getTelefono2());
                email.setText(Proyecto.Principal.Contactos.get(i).getEmail());
                dia.setText(Integer.toString(Proyecto.Principal.Contactos.get(i).getDia()));
                mes.setText(Integer.toString(Proyecto.Principal.Contactos.get(i).getMes()));
                año.setText(Integer.toString(Proyecto.Principal.Contactos.get(i).getAño()));
                if(dia.getText().equals("0")&&mes.getText().equals("0")&&año.getText().equals("0")){
                    dia.setText("");
                    mes.setText("");
                    año.setText("");
                }
            }
        }
        if(esta==false){Proyecto.Principal.mensaje="CONTACTO NO ENCONTRADO";
                Proyecto.Principal.v.setVisible(true);}
        
    }//GEN-LAST:event_telefonomodificarActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        
    }//GEN-LAST:event_nombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eliminar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JLabel Cuaderno;
    private javax.swing.JButton Enviar;
    private javax.swing.JLabel Telefonoabuscar1;
    private javax.swing.JLabel Telefonoabuscar2;
    private javax.swing.JButton agregarcontacto;
    private javax.swing.JLabel agregarcontacto1;
    private javax.swing.JLabel agregarcontacto2;
    private javax.swing.JTextField apellido1;
    private javax.swing.JTextField apellido2;
    private javax.swing.JTextField año;
    private javax.swing.JButton busqueda;
    private javax.swing.JButton calendario;
    private javax.swing.JLabel carteleliminar;
    private javax.swing.JTextField dia;
    private javax.swing.JButton eliminar;
    private javax.swing.JTextField email;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabelFechanacimiento;
    private javax.swing.JLabel jLabelapellido;
    private javax.swing.JLabel jLabelapellido2;
    private javax.swing.JLabel jLabelaño;
    private javax.swing.JLabel jLabeldia;
    private javax.swing.JLabel jLabelemail;
    private javax.swing.JLabel jLabelmenu;
    private javax.swing.JLabel jLabelmes;
    private javax.swing.JLabel jLabelnombre;
    private javax.swing.JLabel jLabeltelefono1;
    private javax.swing.JLabel jLabeltelefono2;
    private javax.swing.JButton listarcontactos;
    private javax.swing.JButton menu;
    private javax.swing.JTextField mes;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField nombre;
    private javax.swing.JLabel presionar;
    private javax.swing.JTextField telefono1;
    private javax.swing.JTextField telefono2;
    private javax.swing.JTextField telefonoabuscar;
    private javax.swing.JButton telefonomodificar;
    // End of variables declaration//GEN-END:variables
}
