/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;


import java.io.BufferedOutputStream;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;


/**
 *
 * @author IDEMNIAS
 */
public class Listar extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Listar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregarcontacto = new javax.swing.JButton();
        Agregar = new javax.swing.JButton();
        listarcontactos = new javax.swing.JButton();
        busqueda = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        calendario = new javax.swing.JButton();
        menu = new javax.swing.JButton();
        jLabelmenu = new javax.swing.JLabel();
        agregarcontacto1 = new javax.swing.JLabel();
        agregarcontacto2 = new javax.swing.JLabel();
        jLabelnombre1 = new javax.swing.JLabel();
        jLabelapellido3 = new javax.swing.JLabel();
        jLabelapellido4 = new javax.swing.JLabel();
        jLabeltelefono3 = new javax.swing.JLabel();
        jLabeltelefono4 = new javax.swing.JLabel();
        jLabelemail1 = new javax.swing.JLabel();
        email1 = new javax.swing.JTextField();
        telefono3 = new javax.swing.JTextField();
        telefono4 = new javax.swing.JTextField();
        apellido4 = new javax.swing.JTextField();
        apellido3 = new javax.swing.JTextField();
        nombre1 = new javax.swing.JTextField();
        jLabeldia1 = new javax.swing.JLabel();
        jLabelmes1 = new javax.swing.JLabel();
        jLabelaño1 = new javax.swing.JLabel();
        jLabelFechanacimiento1 = new javax.swing.JLabel();
        mes1 = new javax.swing.JTextField();
        dia1 = new javax.swing.JTextField();
        años1 = new javax.swing.JTextField();
        años = new javax.swing.JTextField();
        año1 = new javax.swing.JTextField();
        año = new javax.swing.JTextField();
        jLabelaño = new javax.swing.JLabel();
        mes = new javax.swing.JTextField();
        jLabelmes = new javax.swing.JLabel();
        dia = new javax.swing.JTextField();
        jLabeldia = new javax.swing.JLabel();
        jLabelFechanacimiento = new javax.swing.JLabel();
        jLabelemail = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabeltelefono2 = new javax.swing.JLabel();
        telefono2 = new javax.swing.JTextField();
        jLabeltelefono1 = new javax.swing.JLabel();
        telefono1 = new javax.swing.JTextField();
        jLabelapellido2 = new javax.swing.JLabel();
        apellido2 = new javax.swing.JTextField();
        jLabelapellido1 = new javax.swing.JLabel();
        apellido1 = new javax.swing.JTextField();
        jLabelnombre = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        atras = new javax.swing.JButton();
        adelante = new javax.swing.JButton();
        Cuaderno = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agregarcontacto.setFont(new java.awt.Font("Simpsonfont", 1, 8)); // NOI18N
        agregarcontacto.setText("AGREGAR");
        agregarcontacto.setBorderPainted(false);
        agregarcontacto.setContentAreaFilled(false);
        agregarcontacto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarcontacto.setFocusable(false);
        agregarcontacto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        agregarcontacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarcontactoActionPerformed(evt);
            }
        });
        getContentPane().add(agregarcontacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 100, 20));

        Agregar.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Listarlisa2.png"))); // NOI18N
        Agregar.setBorderPainted(false);
        Agregar.setContentAreaFilled(false);
        Agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Agregar.setFocusable(false);
        Agregar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Listarlisa3.png"))); // NOI18N
        Agregar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Listarlisa1.png"))); // NOI18N
        Agregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        getContentPane().add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 120, 200));

        listarcontactos.setFont(new java.awt.Font("Simpsonfont", 1, 8)); // NOI18N
        listarcontactos.setText("LISTAR");
        listarcontactos.setBorderPainted(false);
        listarcontactos.setContentAreaFilled(false);
        listarcontactos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listarcontactos.setFocusable(false);
        listarcontactos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        listarcontactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarcontactosActionPerformed(evt);
            }
        });
        getContentPane().add(listarcontactos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 91, 90, 20));

        busqueda.setFont(new java.awt.Font("Simpsonfont", 1, 10)); // NOI18N
        busqueda.setText("BUSQUEDA");
        busqueda.setBorderPainted(false);
        busqueda.setContentAreaFilled(false);
        busqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        busqueda.setFocusPainted(false);
        busqueda.setFocusable(false);
        busqueda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaActionPerformed(evt);
            }
        });
        getContentPane().add(busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 93, 100, 20));

        modificar.setFont(new java.awt.Font("Simpsonfont", 1, 10)); // NOI18N
        modificar.setText("MODIFICAR");
        modificar.setBorderPainted(false);
        modificar.setContentAreaFilled(false);
        modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modificar.setFocusPainted(false);
        modificar.setFocusable(false);
        modificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        getContentPane().add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(639, 95, 110, 20));

        eliminar.setFont(new java.awt.Font("Simpsonfont", 1, 10)); // NOI18N
        eliminar.setText("ELIMINAR");
        eliminar.setBorderPainted(false);
        eliminar.setContentAreaFilled(false);
        eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminar.setFocusable(false);
        eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(865, 95, 110, 20));

        calendario.setFont(new java.awt.Font("Simpsonfont", 1, 10)); // NOI18N
        calendario.setText("CALENDARIO");
        calendario.setBorderPainted(false);
        calendario.setContentAreaFilled(false);
        calendario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calendario.setFocusable(false);
        calendario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        calendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarioActionPerformed(evt);
            }
        });
        getContentPane().add(calendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(985, 88, 100, 30));

        menu.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu2.png"))); // NOI18N
        menu.setBorderPainted(false);
        menu.setContentAreaFilled(false);
        menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu.setFocusPainted(false);
        menu.setFocusable(false);
        menu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu1.png"))); // NOI18N
        menu.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/menu3.png"))); // NOI18N
        menu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 170, 180));

        jLabelmenu.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabelmenu.setForeground(new java.awt.Color(255, 0, 0));
        jLabelmenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelmenu.setText("MENU");
        jLabelmenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelmenu.setFocusable(false);
        getContentPane().add(jLabelmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 80, 20));

        agregarcontacto1.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        agregarcontacto1.setForeground(new java.awt.Color(255, 0, 0));
        agregarcontacto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agregarcontacto1.setText("LISTAR");
        getContentPane().add(agregarcontacto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 140, 50));

        agregarcontacto2.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        agregarcontacto2.setForeground(new java.awt.Color(255, 0, 0));
        agregarcontacto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agregarcontacto2.setText("CONTACTOS");
        getContentPane().add(agregarcontacto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 140, 50));

        jLabelnombre1.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabelnombre1.setText("NOMBRE");
        getContentPane().add(jLabelnombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 155, 130, 50));

        jLabelapellido3.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabelapellido3.setText("APELLIDO 1");
        getContentPane().add(jLabelapellido3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 210, 130, 50));

        jLabelapellido4.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabelapellido4.setText("APELLIDO 2");
        getContentPane().add(jLabelapellido4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 265, 130, 50));

        jLabeltelefono3.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabeltelefono3.setText("TELEFONO 1");
        getContentPane().add(jLabeltelefono3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 320, 130, 50));

        jLabeltelefono4.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabeltelefono4.setText("TELEFONO 2");
        getContentPane().add(jLabeltelefono4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 375, 130, 50));

        jLabelemail1.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabelemail1.setText("EMAIL");
        getContentPane().add(jLabelemail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 430, 130, 50));

        email1.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        email1.setForeground(new java.awt.Color(51, 51, 255));
        email1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email1.setBorder(null);
        email1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        email1.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        email1.setEnabled(false);
        getContentPane().add(email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 435, 330, 40));

        telefono3.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        telefono3.setForeground(new java.awt.Color(51, 51, 255));
        telefono3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        telefono3.setBorder(null);
        telefono3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        telefono3.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        telefono3.setEnabled(false);
        getContentPane().add(telefono3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 325, 330, 40));

        telefono4.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        telefono4.setForeground(new java.awt.Color(51, 51, 255));
        telefono4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        telefono4.setBorder(null);
        telefono4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        telefono4.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        telefono4.setEnabled(false);
        getContentPane().add(telefono4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 380, 330, 40));

        apellido4.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        apellido4.setForeground(new java.awt.Color(51, 51, 255));
        apellido4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        apellido4.setBorder(null);
        apellido4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        apellido4.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        apellido4.setEnabled(false);
        getContentPane().add(apellido4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 270, 330, 40));

        apellido3.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        apellido3.setForeground(new java.awt.Color(51, 51, 255));
        apellido3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        apellido3.setBorder(null);
        apellido3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        apellido3.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        apellido3.setEnabled(false);
        getContentPane().add(apellido3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 215, 330, 40));

        nombre1.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        nombre1.setForeground(new java.awt.Color(51, 51, 255));
        nombre1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombre1.setBorder(null);
        nombre1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nombre1.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        nombre1.setEnabled(false);
        getContentPane().add(nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 160, 330, 40));

        jLabeldia1.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabeldia1.setText("DIA");
        getContentPane().add(jLabeldia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 540, 40, 50));

        jLabelmes1.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabelmes1.setText("MES");
        getContentPane().add(jLabelmes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 540, 60, 50));

        jLabelaño1.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabelaño1.setText("ANO");
        getContentPane().add(jLabelaño1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 540, 60, 50));

        jLabelFechanacimiento1.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabelFechanacimiento1.setText("FECHA NACIMIENTO");
        getContentPane().add(jLabelFechanacimiento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 485, 230, 50));

        mes1.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        mes1.setForeground(new java.awt.Color(51, 51, 255));
        mes1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mes1.setBorder(null);
        mes1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mes1.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        mes1.setEnabled(false);
        getContentPane().add(mes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 545, 70, 40));

        dia1.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        dia1.setForeground(new java.awt.Color(51, 51, 255));
        dia1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dia1.setBorder(null);
        dia1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dia1.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        dia1.setEnabled(false);
        dia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dia1ActionPerformed(evt);
            }
        });
        getContentPane().add(dia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 545, 70, 40));

        años1.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        años1.setForeground(new java.awt.Color(51, 51, 255));
        años1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        años1.setBorder(null);
        años1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        años1.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        años1.setEnabled(false);
        getContentPane().add(años1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 600, 450, 40));

        años.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        años.setForeground(new java.awt.Color(51, 51, 255));
        años.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        años.setBorder(null);
        años.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        años.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        años.setEnabled(false);
        getContentPane().add(años, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 600, 450, 40));

        año1.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        año1.setForeground(new java.awt.Color(51, 51, 255));
        año1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        año1.setBorder(null);
        año1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        año1.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        año1.setEnabled(false);
        getContentPane().add(año1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 545, 160, 40));

        año.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        año.setForeground(new java.awt.Color(51, 51, 255));
        año.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        año.setBorder(null);
        año.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        año.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        año.setEnabled(false);
        getContentPane().add(año, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 545, 160, 40));

        jLabelaño.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabelaño.setText("ANO");
        getContentPane().add(jLabelaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 540, 60, 50));

        mes.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        mes.setForeground(new java.awt.Color(51, 51, 255));
        mes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mes.setBorder(null);
        mes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mes.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        mes.setEnabled(false);
        getContentPane().add(mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 545, 70, 40));

        jLabelmes.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabelmes.setText("MES");
        getContentPane().add(jLabelmes, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 540, 60, 50));

        dia.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        dia.setForeground(new java.awt.Color(51, 51, 255));
        dia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dia.setBorder(null);
        dia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dia.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        dia.setEnabled(false);
        dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaActionPerformed(evt);
            }
        });
        getContentPane().add(dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 545, 70, 40));

        jLabeldia.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabeldia.setText("DIA");
        getContentPane().add(jLabeldia, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, 40, 50));

        jLabelFechanacimiento.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabelFechanacimiento.setText("FECHA NACIMIENTO");
        getContentPane().add(jLabelFechanacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 485, 230, 50));

        jLabelemail.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabelemail.setText("EMAIL");
        getContentPane().add(jLabelemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 130, 50));

        email.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        email.setForeground(new java.awt.Color(51, 51, 255));
        email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email.setBorder(null);
        email.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        email.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        email.setEnabled(false);
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 435, 330, 40));

        jLabeltelefono2.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabeltelefono2.setText("TELEFONO 2");
        getContentPane().add(jLabeltelefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 375, 130, 50));

        telefono2.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        telefono2.setForeground(new java.awt.Color(51, 51, 255));
        telefono2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        telefono2.setBorder(null);
        telefono2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        telefono2.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        telefono2.setEnabled(false);
        getContentPane().add(telefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 330, 40));

        jLabeltelefono1.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabeltelefono1.setText("TELEFONO 1");
        getContentPane().add(jLabeltelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 130, 50));

        telefono1.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        telefono1.setForeground(new java.awt.Color(51, 51, 255));
        telefono1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        telefono1.setBorder(null);
        telefono1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        telefono1.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        telefono1.setEnabled(false);
        getContentPane().add(telefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 325, 330, 40));

        jLabelapellido2.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabelapellido2.setText("APELLIDO 2");
        getContentPane().add(jLabelapellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 265, 130, 50));

        apellido2.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        apellido2.setForeground(new java.awt.Color(51, 51, 255));
        apellido2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        apellido2.setBorder(null);
        apellido2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        apellido2.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        apellido2.setEnabled(false);
        getContentPane().add(apellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 330, 40));

        jLabelapellido1.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabelapellido1.setText("APELLIDO 1");
        getContentPane().add(jLabelapellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 130, 50));

        apellido1.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        apellido1.setForeground(new java.awt.Color(51, 51, 255));
        apellido1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        apellido1.setBorder(null);
        apellido1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        apellido1.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        apellido1.setEnabled(false);
        getContentPane().add(apellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 215, 330, 40));

        jLabelnombre.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        jLabelnombre.setText("NOMBRE");
        getContentPane().add(jLabelnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 155, 130, 50));

        nombre.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        nombre.setForeground(new java.awt.Color(51, 51, 255));
        nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombre.setBorder(null);
        nombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nombre.setDisabledTextColor(new java.awt.Color(51, 51, 255));
        nombre.setEnabled(false);
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 330, 40));

        atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Atras2.png"))); // NOI18N
        atras.setBorderPainted(false);
        atras.setContentAreaFilled(false);
        atras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atras.setFocusable(false);
        atras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Atras1.png"))); // NOI18N
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        getContentPane().add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 640, 450, 240));

        adelante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Adelante 1.png"))); // NOI18N
        adelante.setBorderPainted(false);
        adelante.setContentAreaFilled(false);
        adelante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adelante.setFocusable(false);
        adelante.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Adelante 2.png"))); // NOI18N
        adelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adelanteActionPerformed(evt);
            }
        });
        getContentPane().add(adelante, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 640, 500, 240));

        Cuaderno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuadernoagenda.png"))); // NOI18N
        getContentPane().add(Cuaderno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wallpapers-los-sipmsons-9.jpg"))); // NOI18N
        fondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1000));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listarcontactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarcontactosActionPerformed
    
    }//GEN-LAST:event_listarcontactosActionPerformed

    private void busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaActionPerformed
        Proyecto.Principal.contador=0;
        this.setVisible(false);
        Proyecto.Principal.b.setVisible(true);
    }//GEN-LAST:event_busquedaActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        Proyecto.Principal.contador=0;
        this.setVisible(false);
        Proyecto.Principal.md.setVisible(true);
    }//GEN-LAST:event_modificarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        Proyecto.Principal.contador=0;
        this.setVisible(false);
        Proyecto.Principal.e.setVisible(true);
    }//GEN-LAST:event_eliminarActionPerformed

    private void calendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarioActionPerformed
        Proyecto.Principal.contador=0;
        this.setVisible(false);
        Proyecto.Principal.c.setVisible(true);
    }//GEN-LAST:event_calendarioActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarActionPerformed

    private void agregarcontactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarcontactoActionPerformed
        Proyecto.Principal.contador=0;
        this.setVisible(false);
        Proyecto.Principal.a.setVisible(true);
    }//GEN-LAST:event_agregarcontactoActionPerformed

    private void dia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dia1ActionPerformed

    private void diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaActionPerformed

    }//GEN-LAST:event_diaActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.nombre.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.apellido1.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.apellido2.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.telefono1.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.telefono2.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.email.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabelFechanacimiento.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.dia.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.mes.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.año.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.agregarcontacto1.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.agregarcontacto2.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabelnombre.setFont(Proyecto.Principal.f.MyFont(1, 18f));
       this.jLabelapellido1.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabelapellido2.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabeltelefono1.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabeltelefono2.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabelemail.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabeldia.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabelmes.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabelaño.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.busqueda.setFont(Proyecto.Principal.f.MyFont(1, 10f));
        this.modificar.setFont(Proyecto.Principal.f.MyFont(1, 10f));
        this.eliminar.setFont(Proyecto.Principal.f.MyFont(1, 10f));
        this.calendario.setFont(Proyecto.Principal.f.MyFont(1, 9f));
        this.agregarcontacto.setFont(Proyecto.Principal.f.MyFont(1, 10f));
        this.listarcontactos.setFont(Proyecto.Principal.f.MyFont(1, 10f));
        this.años.setFont(Proyecto.Principal.f.MyFont(1, 18f));
       
        this.nombre1.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.apellido4.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.apellido3.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.telefono3.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.telefono4.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.email1.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabelFechanacimiento1.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.dia1.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.mes1.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.año1.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabelnombre1.setFont(Proyecto.Principal.f.MyFont(1, 18f));
       this.jLabelapellido3.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabelapellido4.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabeltelefono3.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabeltelefono4.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabelemail1.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabeldia1.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabelmes1.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabelaño1.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.años1.setFont(Proyecto.Principal.f.MyFont(1, 18f));
        this.jLabelmenu.setFont(Proyecto.Principal.f.MyFont(1, 18f));
      
        if(Proyecto.Principal.contador%2==0&&Proyecto.Principal.Contactos.size()>Proyecto.Principal.contador){ 
                nombre.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getNombre());
                apellido1.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getApellido1());
                apellido2.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getApellido2());
                telefono1.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getTelefono1());
                telefono2.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getTelefono2());
                email.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getEmail());
                dia.setText(Integer.toString(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getDia()));
                mes.setText(Integer.toString(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getMes()));
                año.setText(Integer.toString(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getAño()));
                años.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).cumpleaños()); 
                if(dia.getText().equals("0")&&mes.getText().equals("0")&&año.getText().equals("0")){
                    dia.setText("");
                    mes.setText("");
                    año.setText("");
            }}else{
        nombre.setText("");
        apellido1.setText("");
        apellido2.setText("");
        telefono1.setText("");
        telefono2.setText("");
        email.setText("");
        dia.setText("");
        mes.setText("");
        año.setText("");
        años.setText("");
}
        
            Proyecto.Principal.contador++;
            if(Proyecto.Principal.contador%2==1&&Proyecto.Principal.Contactos.size()>Proyecto.Principal.contador){
                nombre1.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getNombre());
                apellido3.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getApellido1());
                apellido4.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getApellido2());
                telefono3.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getTelefono1());
                telefono4.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getTelefono2());
                email1.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getEmail());
                dia1.setText(Integer.toString(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getDia()));
                mes1.setText(Integer.toString(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getMes()));
                año1.setText(Integer.toString(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getAño()));
                años1.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).cumpleaños());
                if(dia1.getText().equals("0")&&mes1.getText().equals("0")&&año1.getText().equals("0")){
                    dia1.setText("");
                    mes1.setText("");
                    año1.setText("");
            }
            }
            else{
        nombre1.setText("");
        apellido3.setText("");
        apellido4.setText("");
        telefono3.setText("");
        telefono4.setText("");
        email1.setText("");
        dia1.setText("");
        mes1.setText("");
        año1.setText("");
        años1.setText("");
}
            Proyecto.Principal.contador++;
    }//GEN-LAST:event_formWindowActivated

    private void adelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adelanteActionPerformed
if(Proyecto.Principal.Contactos.size()>Proyecto.Principal.contador){
        if(Proyecto.Principal.contador%2==0){
                nombre.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getNombre());
                apellido1.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getApellido1());
                apellido2.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getApellido2());
                telefono1.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getTelefono1());
                telefono2.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getTelefono2());
                email.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getEmail());
                dia.setText(Integer.toString(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getDia()));
                mes.setText(Integer.toString(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getMes()));
                año.setText(Integer.toString(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getAño()));
                años.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).cumpleaños()); 
                if(dia.getText().equals("0")&&mes.getText().equals("0")&&año.getText().equals("0")){
                    dia.setText("");
                    mes.setText("");
                    año.setText("");
            }
                Proyecto.Principal.contador++;
        }
        
        if(Proyecto.Principal.contador%2==1&&Proyecto.Principal.Contactos.size()>Proyecto.Principal.contador){
                nombre1.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getNombre());
                apellido3.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getApellido1());
                apellido4.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getApellido2());
                telefono3.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getTelefono1());
                telefono4.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getTelefono2());
                email1.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getEmail());
                dia1.setText(Integer.toString(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getDia()));
                mes1.setText(Integer.toString(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getMes()));
                año1.setText(Integer.toString(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getAño()));
                años1.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).cumpleaños());
                if(dia1.getText().equals("0")&&mes1.getText().equals("0")&&año1.getText().equals("0")){
                    dia1.setText("");
                    mes1.setText("");
                    año1.setText("");
            }
        }
        else{
        nombre1.setText("");
        apellido3.setText("");
        apellido4.setText("");
        telefono3.setText("");
        telefono4.setText("");
        email1.setText("");
        dia1.setText("");
        mes1.setText("");
        año1.setText("");
        años1.setText("");
}Proyecto.Principal.contador++;
}else {}

    }//GEN-LAST:event_adelanteActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        if(Proyecto.Principal.contador>2){
            Proyecto.Principal.contador=Proyecto.Principal.contador-4;
            if(Proyecto.Principal.contador%2==0){
                nombre.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getNombre());
                apellido1.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getApellido1());
                apellido2.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getApellido2());
                telefono1.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getTelefono1());
                telefono2.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getTelefono2());
                email.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getEmail());
                dia.setText(Integer.toString(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getDia()));
                mes.setText(Integer.toString(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getMes()));
                año.setText(Integer.toString(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getAño()));
                años.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).cumpleaños());
                if(dia.getText().equals("0")&&mes.getText().equals("0")&&año.getText().equals("0")){
                    dia.setText("");
                    mes.setText("");
                    año.setText("");
            }
                Proyecto.Principal.contador++;
            }

            if(Proyecto.Principal.contador%2==1){
                nombre1.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getNombre());
                apellido3.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getApellido1());
                apellido4.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getApellido2());
                telefono3.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getTelefono1());
                telefono4.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getTelefono2());
                email1.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getEmail());
                dia1.setText(Integer.toString(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getDia()));
                mes1.setText(Integer.toString(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getMes()));
                año1.setText(Integer.toString(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).getAño()));
                años1.setText(Proyecto.Principal.Contactos.get(Proyecto.Principal.contador).cumpleaños());
                if(dia1.getText().equals("0")&&mes1.getText().equals("0")&&año1.getText().equals("0")){
                    dia1.setText("");
                    mes1.setText("");
                    año1.setText("");
            }
            }Proyecto.Principal.contador++;
        }else{}
    }//GEN-LAST:event_atrasActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed
        this.setVisible(false);
        Proyecto.Principal.m.setVisible(true);
    }//GEN-LAST:event_menuActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregarcontacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregarcontacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregarcontacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregarcontacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregarcontacto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JLabel Cuaderno;
    private javax.swing.JButton adelante;
    private javax.swing.JButton agregarcontacto;
    private javax.swing.JLabel agregarcontacto1;
    private javax.swing.JLabel agregarcontacto2;
    private javax.swing.JTextField apellido1;
    private javax.swing.JTextField apellido2;
    private javax.swing.JTextField apellido3;
    private javax.swing.JTextField apellido4;
    private javax.swing.JButton atras;
    private javax.swing.JTextField año;
    private javax.swing.JTextField año1;
    private javax.swing.JTextField años;
    private javax.swing.JTextField años1;
    private javax.swing.JButton busqueda;
    private javax.swing.JButton calendario;
    private javax.swing.JTextField dia;
    private javax.swing.JTextField dia1;
    private javax.swing.JButton eliminar;
    private javax.swing.JTextField email;
    private javax.swing.JTextField email1;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabelFechanacimiento;
    private javax.swing.JLabel jLabelFechanacimiento1;
    private javax.swing.JLabel jLabelapellido1;
    private javax.swing.JLabel jLabelapellido2;
    private javax.swing.JLabel jLabelapellido3;
    private javax.swing.JLabel jLabelapellido4;
    private javax.swing.JLabel jLabelaño;
    private javax.swing.JLabel jLabelaño1;
    private javax.swing.JLabel jLabeldia;
    private javax.swing.JLabel jLabeldia1;
    private javax.swing.JLabel jLabelemail;
    private javax.swing.JLabel jLabelemail1;
    private javax.swing.JLabel jLabelmenu;
    private javax.swing.JLabel jLabelmes;
    private javax.swing.JLabel jLabelmes1;
    private javax.swing.JLabel jLabelnombre;
    private javax.swing.JLabel jLabelnombre1;
    private javax.swing.JLabel jLabeltelefono1;
    private javax.swing.JLabel jLabeltelefono2;
    private javax.swing.JLabel jLabeltelefono3;
    private javax.swing.JLabel jLabeltelefono4;
    private javax.swing.JButton listarcontactos;
    private javax.swing.JButton menu;
    private javax.swing.JTextField mes;
    private javax.swing.JTextField mes1;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField nombre1;
    private javax.swing.JTextField telefono1;
    private javax.swing.JTextField telefono2;
    private javax.swing.JTextField telefono3;
    private javax.swing.JTextField telefono4;
    // End of variables declaration//GEN-END:variables
}
