/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;


import java.awt.HeadlessException;
import java.io.BufferedOutputStream;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author IDEMNIAS
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
     
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listarcontactos1 = new javax.swing.JButton();
        listarcontactos = new javax.swing.JButton();
        busqueda = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        calendario = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        Salir = new javax.swing.JLabel();
        Agregar = new javax.swing.JLabel();
        Contacto = new javax.swing.JLabel();
        Listar = new javax.swing.JLabel();
        Contactos = new javax.swing.JLabel();
        Busqueda = new javax.swing.JLabel();
        Modificar = new javax.swing.JLabel();
        Contacto1 = new javax.swing.JLabel();
        Eliminar = new javax.swing.JLabel();
        Calendario = new javax.swing.JLabel();
        Contacto2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listarcontactos1.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        listarcontactos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregarcontactos2.png"))); // NOI18N
        listarcontactos1.setBorderPainted(false);
        listarcontactos1.setContentAreaFilled(false);
        listarcontactos1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listarcontactos1.setFocusable(false);
        listarcontactos1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregarcontactos3.png"))); // NOI18N
        listarcontactos1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregarcontactos1.png"))); // NOI18N
        listarcontactos1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        listarcontactos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarcontactos1ActionPerformed(evt);
            }
        });
        getContentPane().add(listarcontactos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 240, 190));

        listarcontactos.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        listarcontactos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Listarlisa2.png"))); // NOI18N
        listarcontactos.setBorderPainted(false);
        listarcontactos.setContentAreaFilled(false);
        listarcontactos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listarcontactos.setFocusable(false);
        listarcontactos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Listarlisa3.png"))); // NOI18N
        listarcontactos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Listarlisa1.png"))); // NOI18N
        listarcontactos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        listarcontactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarcontactosActionPerformed(evt);
            }
        });
        getContentPane().add(listarcontactos, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 85, 120, 200));

        busqueda.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        busqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Busqueda2.png"))); // NOI18N
        busqueda.setText("BUSQUEDA");
        busqueda.setBorderPainted(false);
        busqueda.setContentAreaFilled(false);
        busqueda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        busqueda.setFocusPainted(false);
        busqueda.setFocusable(false);
        busqueda.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Busqueda3.png"))); // NOI18N
        busqueda.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Busqueda1.png"))); // NOI18N
        busqueda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaActionPerformed(evt);
            }
        });
        getContentPane().add(busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 90, 160, 200));

        modificar.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar2.png"))); // NOI18N
        modificar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        modificar.setBorderPainted(false);
        modificar.setContentAreaFilled(false);
        modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modificar.setDefaultCapable(false);
        modificar.setFocusPainted(false);
        modificar.setFocusable(false);
        modificar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar3.png"))); // NOI18N
        modificar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar1.png"))); // NOI18N
        modificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        getContentPane().add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 635, 150, 200));

        eliminar.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar homer2.png"))); // NOI18N
        eliminar.setBorderPainted(false);
        eliminar.setContentAreaFilled(false);
        eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminar.setDefaultCapable(false);
        eliminar.setFocusPainted(false);
        eliminar.setFocusable(false);
        eliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar homer3.png"))); // NOI18N
        eliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar homer1.png"))); // NOI18N
        eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 655, 250, 180));

        calendario.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        calendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendario2.png"))); // NOI18N
        calendario.setBorderPainted(false);
        calendario.setContentAreaFilled(false);
        calendario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calendario.setFocusPainted(false);
        calendario.setFocusable(false);
        calendario.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendario3.png"))); // NOI18N
        calendario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendario1.png"))); // NOI18N
        calendario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        calendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarioActionPerformed(evt);
            }
        });
        getContentPane().add(calendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1095, 655, 160, 200));

        salir.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir2.png"))); // NOI18N
        salir.setBorderPainted(false);
        salir.setContentAreaFilled(false);
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.setFocusPainted(false);
        salir.setFocusable(false);
        salir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir3.png"))); // NOI18N
        salir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir1.png"))); // NOI18N
        salir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 360, 100, 200));

        Salir.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        Salir.setForeground(new java.awt.Color(255, 0, 0));
        Salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Salir.setText("SALIR");
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1495, 570, 70, 30));

        Agregar.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        Agregar.setForeground(new java.awt.Color(255, 0, 0));
        Agregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Agregar.setText("AGREGAR");
        getContentPane().add(Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 140, 50));

        Contacto.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        Contacto.setForeground(new java.awt.Color(255, 0, 0));
        Contacto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Contacto.setText("CONTACTO");
        getContentPane().add(Contacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 300, 140, 50));

        Listar.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        Listar.setForeground(new java.awt.Color(255, 0, 0));
        Listar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Listar.setText("LISTAR");
        getContentPane().add(Listar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 270, 140, 50));

        Contactos.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        Contactos.setForeground(new java.awt.Color(255, 0, 0));
        Contactos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Contactos.setText("CONTACTOS");
        getContentPane().add(Contactos, new org.netbeans.lib.awtextra.AbsoluteConstraints(697, 300, 140, 50));

        Busqueda.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        Busqueda.setForeground(new java.awt.Color(255, 0, 0));
        Busqueda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Busqueda.setText("BUSQUEDA");
        getContentPane().add(Busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 280, 140, 50));

        Modificar.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        Modificar.setForeground(new java.awt.Color(255, 0, 0));
        Modificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Modificar.setText("MODIFICAR");
        getContentPane().add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 820, 140, 50));

        Contacto1.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        Contacto1.setForeground(new java.awt.Color(255, 0, 0));
        Contacto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Contacto1.setText("CONTACTO");
        getContentPane().add(Contacto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 850, 140, 50));

        Eliminar.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        Eliminar.setForeground(new java.awt.Color(255, 0, 0));
        Eliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Eliminar.setText("ELIMINAR");
        getContentPane().add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 820, 140, 50));

        Calendario.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        Calendario.setForeground(new java.awt.Color(255, 0, 0));
        Calendario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Calendario.setText("CALENDARIO");
        getContentPane().add(Calendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 830, 160, 50));

        Contacto2.setFont(new java.awt.Font("Simpsonfont", 1, 18)); // NOI18N
        Contacto2.setForeground(new java.awt.Color(255, 0, 0));
        Contacto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Contacto2.setText("CONTACTO");
        getContentPane().add(Contacto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(708, 850, 140, 50));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/wallpapers-los-sipmsons-9.jpg"))); // NOI18N
        fondo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 1000));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listarcontactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarcontactosActionPerformed
        this.setVisible(false);
        Proyecto.Principal.l.setVisible(true);
    }//GEN-LAST:event_listarcontactosActionPerformed

    private void busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaActionPerformed
        this.setVisible(false);
        Proyecto.Principal.b.setVisible(true);
    }//GEN-LAST:event_busquedaActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        this.setVisible(false);
        Proyecto.Principal.md.setVisible(true);
    }//GEN-LAST:event_modificarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        this.setVisible(false);
        Proyecto.Principal.e.setVisible(true);
    }//GEN-LAST:event_eliminarActionPerformed

    private void calendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarioActionPerformed
        this.setVisible(false);
        Proyecto.Principal.c.setVisible(true);
    }//GEN-LAST:event_calendarioActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
           
        try{ObjectOutputStream escribircontactos = new ObjectOutputStream(new BufferedOutputStream(new FileOutputStream("contacto")));
        escribircontactos.writeObject(Proyecto.Principal.Contactos);
        escribircontactos.flush();
        escribircontactos.close();
        }catch (Exception ex ){
            System.out.println("error de escritura");
            System.out.println(ex.getMessage());
        }
        this.dispose();
        Proyecto.Principal.a.dispose();
        Proyecto.Principal.b.dispose();
        Proyecto.Principal.c.dispose();
        Proyecto.Principal.e.dispose();
        Proyecto.Principal.l.dispose();
        Proyecto.Principal.md.dispose();
        Proyecto.Principal.v.dispose();
        Proyecto.Principal.vc.dispose();
     
        
        
        
    }//GEN-LAST:event_salirActionPerformed

    private void listarcontactos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarcontactos1ActionPerformed
        this.setVisible(false);
        Proyecto.Principal.a.setVisible(true);
    }//GEN-LAST:event_listarcontactos1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    this.Agregar.setFont(Proyecto.Principal.f.MyFont(1, 18f));
    this.Contacto.setFont(Proyecto.Principal.f.MyFont(1, 18f));
    this.Contactos.setFont(Proyecto.Principal.f.MyFont(1, 18f));
    this.Modificar.setFont(Proyecto.Principal.f.MyFont(1, 18f));
    this.Eliminar.setFont(Proyecto.Principal.f.MyFont(1, 18f));
    this.Busqueda.setFont(Proyecto.Principal.f.MyFont(1, 18f));
    this.Listar.setFont(Proyecto.Principal.f.MyFont(1, 18f));
    this.Contacto1.setFont(Proyecto.Principal.f.MyFont(1, 18f));
    this.Contacto2.setFont(Proyecto.Principal.f.MyFont(1, 18f));
    this.Calendario.setFont(Proyecto.Principal.f.MyFont(1, 18f));
    this.Salir.setFont(Proyecto.Principal.f.MyFont(1, 18f));
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Agregar;
    private javax.swing.JLabel Busqueda;
    private javax.swing.JLabel Calendario;
    private javax.swing.JLabel Contacto;
    private javax.swing.JLabel Contacto1;
    private javax.swing.JLabel Contacto2;
    private javax.swing.JLabel Contactos;
    private javax.swing.JLabel Eliminar;
    private javax.swing.JLabel Listar;
    private javax.swing.JLabel Modificar;
    private javax.swing.JLabel Salir;
    private javax.swing.JButton busqueda;
    private javax.swing.JButton calendario;
    private javax.swing.JButton eliminar;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton listarcontactos;
    private javax.swing.JButton listarcontactos1;
    private javax.swing.JButton modificar;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables

}
